# Generated by Django 3.2 on 2021-06-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('objectID', models.IntegerField()),
                ('type', models.IntegerField()),
                ('sendID', models.IntegerField()),
                ('replyID', models.IntegerField()),
                ('text', models.CharField(max_length=110)),
                ('sendtime', models.CharField(max_length=30)),
            ],
        ),
    ]
