# Generated by Django 3.2 on 2021-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyid', models.IntegerField()),
                ('infromid', models.IntegerField()),
            ],
        ),
    ]
