# Generated by Django 3.2 on 2021-06-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inform', '0002_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='infromid',
            new_name='informid',
        ),
    ]
