# Generated by Django 3.2 on 2021-05-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemandInfo',
            fields=[
                ('demandid', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('demandname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('categoryid', models.IntegerField()),
                ('uploadtime', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('onsale', models.BooleanField()),
            ],
        ),
    ]
