# Generated by Django 3.2 on 2021-05-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('catid', models.IntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GoodImg',
            fields=[
                ('imgid', models.IntegerField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='img')),
            ],
        ),
    ]
