# Generated by Django 3.2 on 2021-05-22 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodimg',
            name='img',
            field=models.ImageField(blank=True, upload_to='img'),
        ),
    ]
