# Generated by Django 3.2 on 2021-05-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0003_alter_goodimg_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodInfo',
            fields=[
                ('goodid', models.IntegerField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('goodname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('categoryid', models.IntegerField()),
                ('uploadtime', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('onsale', models.BooleanField()),
            ],
        ),
    ]
