# Generated by Django 3.2 on 2021-05-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0004_goodinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GImg',
            fields=[
                ('imgid', models.IntegerField(primary_key=True, serialize=False)),
                ('goodid', models.IntegerField(blank=True)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='GoodImg',
        ),
    ]
