# Generated by Django 3.2 on 2021-05-26 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good', '0005_auto_20210524_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodCollect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('goodID', models.IntegerField()),
            ],
        ),
    ]
