# Generated by Django 3.2 on 2021-05-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210521_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userheadshot',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('headshot', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
