# Generated by Django 3.2 on 2021-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userheadshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
                ('sex', models.IntegerField(blank=True)),
                ('grade', models.IntegerField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=15)),
                ('location', models.IntegerField(blank=True)),
                ('tradecount', models.IntegerField(blank=True)),
                ('score', models.FloatField(blank=True)),
            ],
        ),
    ]
