# Generated by Django 3.2 on 2021-05-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210526_1756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCollect',
        ),
    ]
