# Generated by Django 3.2 on 2021-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_delete_usercollect'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanInfo',
            fields=[
                ('userID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
